// automatically generated by the FlatBuffers compiler, do not modify

package symbol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// CodeCompleteResults represents a list of vim complete-items dictionary.
type CodeCompleteResults struct {
	_tab flatbuffers.Table
}

func GetRootAsCodeCompleteResults(buf []byte, offset flatbuffers.UOffsetT) *CodeCompleteResults {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CodeCompleteResults{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CodeCompleteResults) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CodeCompleteResults) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CodeCompleteResults) Results(obj *CompleteItem, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *CodeCompleteResults) ResultsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func CodeCompleteResultsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CodeCompleteResultsAddResults(builder *flatbuffers.Builder, Results flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(Results), 0)
}
func CodeCompleteResultsStartResultsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CodeCompleteResultsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
